// The four built-in sample photos. They are procedural stand-ins (we cannot ship real photos),
// generated by dev/samples.html + dev/sample-gen.js and baked to img/samples/<id>.jpg (1024 px)
// and <id>-thumb.jpg (160 px), so the app only fetches a small JPEG and never compiles a shader.

export const SAMPLES = [
  { id: 'portrait', name: 'Portrait',
    alt: 'A classical plaster bust of a young man with sculpted wavy hair, lit softly from the upper left against a grey studio backdrop' },
  { id: 'pet', name: 'Cat',
    alt: 'Portrait of a tabby-and-white cat with bright amber-green eyes and white whiskers on a pale background' },
  { id: 'landmark', name: 'Lighthouse',
    alt: 'A red-and-white striped lighthouse on a dark rocky headland at sunset, the sun low over the sea to its right' },
  { id: 'logo', name: 'Emblem',
    alt: 'A black-and-white round emblem: two snow-capped peaks under a sun, with two waves below, inside a double ring' },
];

const BASE = new URL('../img/samples/', import.meta.url);
const known = id => SAMPLES.some(s => s.id === id);

export function imageUrl(id) { return new URL(`${id}.jpg`, BASE).href; }
export function thumbUrl(id) { return new URL(`${id}-thumb.jpg`, BASE).href; }

// The fetched bytes are kept per id (a few hundred KB at most), so switching back to a sample
// does not hit the network again; every call still gets its own ImageBitmap to own and close.
const blobs = new Map();

export async function loadSample(id) {
  if (!known(id)) throw new Error(`Unknown sample '${id}'`);
  if (!blobs.has(id)) {
    const job = fetch(imageUrl(id)).then(r => {
      if (!r.ok) throw new Error(`Could not load the sample '${id}' (HTTP ${r.status}).`);
      return r.blob();
    });
    blobs.set(id, job);
    job.catch(() => blobs.delete(id));   // a failed fetch can be retried
  }
  return createImageBitmap(await blobs.get(id));
}
